### ISSUE TITLE
Heel erg specifieke selectors

### ISSUE THREAD

**Issue by vasilisvg** [melvinr/CSS-to-the-rescue#3]
Nogal veel heel specifieke selectors. Probeer niet dieper dan maximaal 3 te gaan, het begint op https://github.com/melvinr/CSS-to-the-rescue/blob/master/css/style.css#L87
Moet dit echt zo specifiek? Of kan dit ook gewoon voor elke input gelden? https://github.com/melvinr/CSS-to-the-rescue/blob/master/css/style.css#L169

**Comment by melvinr** [comment]
Edited selectors to be less specific
